config/routes.rb
Rails.application.routes.draw do
  resources :jobs
get '/' => 'users#signin'
get '/' => 'users#signin'
post '/sessions' => 'sessions#create'
post '/users' => 'users#create'
get '/dashboard' => 'jobs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    def index
        @jobs = Job.all
    end
    def show
        @job = Job.find(params[:id])
    end
    def new
        @job = Job.new
    end
    def create
    @job = Job.new(job_params) 
        if @job.save
           redirect_to jobs_path
        else 
           render :new
        end
    end 
    

def edit
    @job = Job.find(params[:id])
end
def update
  @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
end
def destroy
  @job = Job.find(params[:id])
  @job.destroy
  redirect_to jobs_path
end

private
def job_params
   params.require(:job).permit(:title, :desc, :salary,)
end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
def create

    user = User.find_by(email:login_params[:email])
    if user && user.authenticate(login_params[:password])
        session[:user_id] = user.id
        redirect_to "/dashboard" 
        
    else
        flash[:login_errors]=["invalid credentials"]
        redirect_to '/'
        
    end
end

    private
        def login_params
            params.require(:login).permit(:email, :password)
            
        end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		
	end
	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
			redirect_to '/dashboard'
		else
			flash[:register_errors] = user.errors.full_messages
			redirect_to '/'
		end
	end	

	private
	def user_params
		params.require(:user).permit(:name, :email, :password, :passowrd_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/edit.html.erb
<%= form_for @job do |n| %>
<div>
  <%= n.label :title %>
  <%= n.text_field :title %>
</div>
<div>
  <%= n.label :desc%>
  <%= n.text_area :desc %>
</div>
<div>
  <%= n.label :salary%>
  <%= n.number_field :salary %>
</div>
<div>
  <%= n.submit %>
</div>
<% end %>

app/views/jobs/index.html.erb
<!DOCTYPE html>
<html>
<body>

<h1>
	Jobs
</h1>
<hr>
<td> <button><%= link_to " myapplication" %> </button></td>
<table>
<thead>
<th>Job Title</th>
<th>Description</th>
<th>Salary</th>
</thead>

<% @jobs.each do |job| %>
<tr>
    <td><%= job.title -%> </td> 
	<td><%= job.desc -%></td>
    <td><%= job.salary -%></td>
    <td><button><%= link_to "Edit", edit_job_path(job) %></button></td>
	<td> <button><%= link_to "Delete", job, method: :delete, data: { confirm: "delete this job?"} %></button> </td>
	<td><button> <%= link_to "Apply this job", edit_job_path(job) %></button></td>
</tr>
<% end -%>
	<td><button> <%= link_to "add new Job", new_job_path %></button> </td>
</table>

<hr>
</body>
</html>

app/views/jobs/myapplication.html.erb
!DOCTYPE html>
<html>
<body>

<h1>
	my application
</h1>
<hr>
<table>
<thead>
<th>Job Title</th>
<th>Description</th>
<th>Salary</th>
</thead>

<% @jobs.each do |job| %>
<tr>
    <td><%= job.title -%> </td> 
	<td><%= job.desc -%></td>
    <td><%= job.salary -%></td>
	<td> <%= link_to "Delete", job, method: :delete, data: { confirm: "delete this job?"} %> </td>
</tr>
<% end -%>
</table>

<hr>
</body>
</html>

app/views/jobs/new.html.erb
<%= form_for @job do |n| %>
<div>
  <%= n.label :title %>
  <%= n.text_field :title %>
</div>
<div>
  <%= n.label :desc%>
  <%= n.text_area :desc %>
</div>
<div>
  <%= n.label :salary%>
  <%= n.number_field :salary %>
</div>
<div>
  <%= n.submit %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JOBApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/signin.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>Login and Registration</title>
  </head>

  <body>
  <h1>Login Page </h1>
  <form action="/sessions" method="POST">

<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
<br>
<input type="email" name="login[email]" placeholder="Enter the Email">
<br>
<input type="password" name="login[password]" placeholder="please Enter Password">	
<br>
<input type="submit" name="submit" class="submit">
</form>

<hr>

<div class="errors">
	<%if flash[:login_errors] %>
	<%if flash[:login_errors].each do |error|  %>
	<p> <%=error%></p>
	<% end -%>
	<% end -%>
</div>

	<% end -%>

<h1>Registration</h1>

<form action="/users" method="POST">
	<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
	<br>
	<input type="name" name="user[name]" placeholder="Enter userName">
	<br>
	<input type="email" name="user[email]" placeholder="Enter Email">
	<br>
	<input type="password" name="user[password]" placeholder="Enter Password">
	<br>
	<input type="password" name="user[password_confirmation]" placeholder="password confirmation">
	<br>
	<input type="submit" name="submit" class="submit">
</form>

<div class="errors">
	<%if flash[:register_errors] %>
	<%if flash[:register_errors].each do |error|  %>
	<p> <%=error%></p>
	<% end -%>
	<% end -%>
</div>
	<% end -%>



  </body>
</html>